"""
PDF report generation for DataPilot.

Converts a cleaned Pandas DataFrame into a formatted PDF summary table,
used as the downloadable report attached to a completed cleaning job.
"""

from __future__ import annotations

import logging
from datetime import datetime
from io import BytesIO

import pandas as pd
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

logger = logging.getLogger(__name__)

# --- layout constants -------------------------------------------------------

PAGE_SIZE = landscape(A4)
MARGIN_LEFT = 10 * mm
MARGIN_RIGHT = 10 * mm
MARGIN_TOP = 12 * mm
MARGIN_BOTTOM = 12 * mm

TABLE_FONT_SIZE = 7
TABLE_CELL_PADDING = 4

# --- palette (matches DataPilot's web UI) ------------------------------------

COLOR_HEADER_BG = colors.HexColor("#171A1F")
COLOR_HEADER_TEXT = colors.white
COLOR_GRID = colors.HexColor("#DEE1E4")


def generate_pdf_report(filename: str, dataframe: pd.DataFrame) -> BytesIO:
    """
    Render a cleaned DataFrame as a downloadable PDF report.

    Args:
        filename: Original CSV filename, shown in the report header.
        dataframe: The cleaned DataFrame to render as a table.

    Returns:
        A seeked-to-start BytesIO buffer containing the PDF bytes.

    Raises:
        ValueError: If `dataframe` is None (an empty DataFrame is allowed
            and renders a "no data" placeholder instead of failing).
    """
    if dataframe is None:
        raise ValueError("generate_pdf_report() requires a DataFrame, got None.")

    buffer = BytesIO()
    document = SimpleDocTemplate(
        buffer,
        pagesize=PAGE_SIZE,
        leftMargin=MARGIN_LEFT,
        rightMargin=MARGIN_RIGHT,
        topMargin=MARGIN_TOP,
        bottomMargin=MARGIN_BOTTOM,
        title=f"DataPilot Report — {filename}",
    )

    elements = [
        *_build_header(filename, dataframe),
        Spacer(1, 12),
        _build_table(dataframe),
        Spacer(1, 12),
        *_build_footer(),
    ]

    try:
        document.build(elements)
    except Exception:
        logger.exception("Failed to build PDF report for '%s'", filename)
        raise

    buffer.seek(0)
    return buffer


def _build_header(filename: str, dataframe: pd.DataFrame) -> list:
    """Title, source filename, and row/column counts."""
    styles = getSampleStyleSheet()
    meta_style = ParagraphStyle(
        "Meta",
        parent=styles["BodyText"],
        textColor=colors.HexColor("#4B515C"),
    )

    return [
        Paragraph("DataPilot — Cleaned Dataset Report", styles["Title"]),
        Spacer(1, 4),
        Paragraph(f"<b>Source file:</b> {_escape(filename)}", styles["BodyText"]),
        Paragraph(
            f"<b>Rows:</b> {len(dataframe):,} &nbsp;&nbsp;&nbsp; "
            f"<b>Columns:</b> {len(dataframe.columns):,}",
            styles["BodyText"],
        ),
        Paragraph(
            f"Generated {datetime.now():%B %d, %Y at %H:%M}",
            meta_style,
        ),
    ]


def _build_table(dataframe: pd.DataFrame) -> Table:
    """Render the DataFrame as a styled, page-repeating Table."""
    if dataframe.empty:
        # A single-row placeholder is simpler than special-casing "no table" downstream.
        return Table([["No rows to display."]], style=_table_style(column_count=1))

    display_df = dataframe.fillna("").astype(str)
    table_data = [list(display_df.columns)] + display_df.values.tolist()
    column_count = len(display_df.columns)

    table = Table(
        table_data,
        colWidths=_column_widths(column_count),
        repeatRows=1,  # repeat the header row on every page
    )
    table.setStyle(_table_style(column_count))
    return table


def _column_widths(column_count: int) -> list[float] | None:
    if column_count <= 0:
        return None
    usable_width = PAGE_SIZE[0] - MARGIN_LEFT - MARGIN_RIGHT
    return [usable_width / column_count] * column_count


def _table_style(column_count: int) -> TableStyle:
    return TableStyle(
        [
            ("BACKGROUND", (0, 0), (-1, 0), COLOR_HEADER_BG),
            ("TEXTCOLOR", (0, 0), (-1, 0), COLOR_HEADER_TEXT),
            ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE", (0, 0), (-1, -1), TABLE_FONT_SIZE),
            ("GRID", (0, 0), (-1, -1), 0.4, COLOR_GRID),
            ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ("LEFTPADDING", (0, 0), (-1, -1), TABLE_CELL_PADDING),
            ("RIGHTPADDING", (0, 0), (-1, -1), TABLE_CELL_PADDING),
            ("TOPPADDING", (0, 0), (-1, -1), TABLE_CELL_PADDING),
            ("BOTTOMPADDING", (0, 0), (-1, -1), TABLE_CELL_PADDING),
        ]
    )


def _build_footer() -> list:
    styles = getSampleStyleSheet()
    return [Paragraph("Generated by DataPilot", styles["BodyText"])]


def _escape(text: str) -> str:
    """Escape XML-unsafe characters before embedding text in a Paragraph."""
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
    )