# Generated by Django 5.2.17 on 2026-08-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_file', models.FileField(upload_to='uploads/')),
                ('cleaned_file', models.FileField(blank=True, null=True, upload_to='cleaned/')),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('issues_found', models.PositiveIntegerField(default=0)),
                ('issues_fixed', models.PositiveIntegerField(default=0)),
                ('rows_removed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
