# Generated by Django 5.2.17 on 2026-08-29 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0003_cleaningjob_dataset'),
        ('datasets', '0002_alter_datasetcolumn_options_dataset_checksum_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cleaningfinding',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='cleaningjob',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='cleaningfinding',
            name='finding_type',
            field=models.CharField(choices=[('missing', 'Missing Value'), ('duplicate', 'Duplicate Row'), ('invalid', 'Invalid Value'), ('formatting', 'Formatting Issue')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cleaningfinding',
            name='fixed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='cleaningfinding',
            name='row_number',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cleaningjob',
            name='issues_fixed',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cleaningjob',
            name='issues_found',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cleaningjob',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='cleaningjob',
            name='row_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cleaningjob',
            name='rows_removed',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cleaningjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='cleaningfinding',
            index=models.Index(fields=['job', 'finding_type'], name='finding_job_type_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningfinding',
            index=models.Index(fields=['job', 'fixed'], name='finding_job_fixed_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningjob',
            index=models.Index(fields=['status', '-created_at'], name='cleaning_status_created_idx'),
        ),
        migrations.AddIndex(
            model_name='cleaningjob',
            index=models.Index(fields=['dataset', '-created_at'], name='cleaning_dataset_created_idx'),
        ),
    ]
