# Generated by Django 5.2.17 on 2026-08-29 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaner', '0004_alter_cleaningfinding_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CleaningJobOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='cleaned/')),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF')], db_index=True, max_length=10)),
                ('filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='cleaner.cleaningjob')),
            ],
            options={
                'ordering': ['file_format', 'id'],
                'indexes': [models.Index(fields=['job', 'file_format'], name='cleaning_output_job_format_idx')],
                'constraints': [models.UniqueConstraint(fields=('job', 'file_format'), name='unique_cleaning_job_output_format')],
            },
        ),
    ]
